on:
  push:
    branches:
      - main

jobs:
  build1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./firmware/m5atom-earth
    steps:
    - name: 🔧 Setup repo
      uses: actions/checkout@v3

    - name: 🔧 Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 🔧 Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: 🔧 Setup Python
      uses: actions/setup-python@v2

    - name: 📦 Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: 📦 Install library dependencies
      run: pio lib -g install 1

    - name: 🚀 Run PlatformIO
      run: pio run

  build2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./firmware/m5atom-env
    steps:
    - name: 🔧 Setup repo
      uses: actions/checkout@v3

    - name: 🔧 Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 🔧 Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: 🔧 Setup Python
      uses: actions/setup-python@v2

    - name: 📦 Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: 📦 Install library dependencies
      run: pio lib -g install 1

    - name: 🚀 Run PlatformIO
      run: pio run

  build3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./firmware/timer-cam
    steps:
    - name: 🔧 Setup repo
      uses: actions/checkout@v3

    - name: 🔧 Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 🔧 Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: 🔧 Setup Python
      uses: actions/setup-python@v2

    - name: 📦 Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: 📦 Install library dependencies
      run: pio lib -g install 1

    - name: 🚀 Run PlatformIO
      run: pio run