on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: 🔧 Setup repo
        uses: actions/checkout@v3

      - name: 🔧 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: 🔧 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Publish app
        run: expo publish --non-interactive
